Repository spencerhall01/Group-13, pull requests merged in 2023-03, with the labels that each got.

#34 Uploading seller use case diagram #29
  SellerUseCaseDiagram.pdf
Labels: documentation

#35 Sequence Diagram for User Story 2
  SequenceDiagramUserStory2.pdf
Labels: documentation

#47 Sequence diagram for user story 2 #23
  SellerSeqDiagram.pdf
Labels: documentation, enhancement

#46 State diagram for user story 2 #36
  SellerStateDiagram.pdf
Labels: documentation

#45 Activity diagram for user story 2 #42
  SellerActivityDiagram.pdf
Labels: documentation

#43 George's activity diagrams #42
  US5ADSellerPrivileges.pdf
  US5SDSellerPrivileges.pdf
  US5StDSellerPrivileges.pdf
  US7ADUserLogout.pdf
  US7SDUserLogout.pdf
  US7StDUserLogout.pdf
Labels: documentation, enhancement

#38 Kyana sprint 2
  Admin Privileges Activity diagram.pdf
  Admin Privileges Sequence Diagram.pdf
  Admin Privileges State diagram.pdf
  Component Diagram.pdf
  Login Activity diagram.pdf
  Login Sequence Diagram.pdf
  Login State diagram.pdf
  admin privileges use case diagram (1).pdf
  admin use case diagram.pdf
  login use case diagram.pdf
Labels: enhancement

#49 Updating Spencer's Branch
  Admin Privileges Activity diagram.pdf
  Admin Privileges Sequence Diagram.pdf
  Admin Privileges State diagram.pdf
  BlankDiagram.pdf
  Component Diagram.pdf
  Intro-to-SE_SRS_Template.doc
  Login Activity diagram.pdf
  Login Sequence Diagram.pdf
  Login State diagram.pdf
  SellerActivityDiagram.pdf
  SellerSeqDiagram.pdf
  SellerStateDiagram.pdf
  SellerUseCaseDiagram.pdf
  SequenceDiagramUserStory2.pdf
  US5ADSellerPrivileges.pdf
  US5SDSellerPrivileges.pdf
  US5StDSellerPrivileges.pdf
  US7ADUserLogout.pdf
  US7SDUserLogout.pdf
  US7StDUserLogout.pdf
  admin privileges use case diagram (1).pdf
  login use case diagram.pdf
Labels: documentation

#52 Upload class diagram #50
  ClassDiagram.pdf
Labels: documentation

#54 Updating Spencer's Branch
  ClassDiagram.pdf
Labels: documentation

#55 MAJOR: End Sprint 2
  diagrams/activity/admin_activity.pdf
  diagrams/activity/buyer_activity.drawio
  diagrams/activity/buyer_activity.pdf
  diagrams/activity/login_activity.pdf
  diagrams/activity/logout_activity.pdf
  diagrams/activity/seller_activity_v1.pdf
  diagrams/activity/seller_activity_v2.pdf
  diagrams/architecture/mvc_architecture.drawio
  diagrams/architecture/mvc_architecture.pdf
  diagrams/class/object_class.pdf
  diagrams/component/search_component.drawio
  diagrams/component/search_component.pdf
  diagrams/component/site_component.pdf
  diagrams/sequence/admin_sequence.pdf
  diagrams/sequence/buyer_sequence.drawio
  diagrams/sequence/buyer_sequence.pdf
  diagrams/sequence/buyer_sequence_alt.pdf
  diagrams/sequence/login_sequence.pdf
  diagrams/sequence/logout_sequence.pdf
  diagrams/sequence/seller_sequence_v1.pdf
  diagrams/sequence/seller_sequence_v2.pdf
  diagrams/state/admin_state.pdf
  diagrams/state/buyer_state.drawio
  diagrams/state/buyer_state.pdf
  diagrams/state/login_state.pdf
  diagrams/state/logout_state.pdf
  diagrams/state/seller_state_v1.pdf
  diagrams/state/seller_state_v2.pdf
  diagrams/use-case/admin_use-case.pdf
  diagrams/use-case/buyer_use-case.drawio
  diagrams/use-case/buyer_use-case.pdf
  diagrams/use-case/combined_use-case.pdf
  diagrams/use-case/login_use-case.pdf
  diagrams/use-case/seller_user-case.pdf
  srs/srs_final.pdf
  srs/srs_george.doc
  srs/srs_kyana.doc
  srs/srs_spencer.doc
  srs/srs_v1.doc
  srs/srs_v2.doc
  srs/srs_v3.doc
  srs/srs_v4.doc
  srs/srs_v5.doc
Labels: documentation
